shop/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from contact_us.views import contact_us

urlpatterns = [
    path('', include('books.urls')),
    path('about/', TemplateView.as_view(template_name='about_faq/about.html'), name='about'),
    path('faq/', TemplateView.as_view(template_name='about_faq/faq.html'), name='faq'),
    path('contact_us/', contact_us, name='contact_us'),
    path('order/', include('order.urls')),
    path('profile/', include('user_authentication.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls'))
]

if settings.DEBUG:
    urlpatterns += [
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
                   + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/books/models.py
from django.db import models
from django.shortcuts import reverse
from django.utils import timezone


class Genre(models.Model):
    """
    Model representing a book genre (e.g. Science Fiction, Non Fiction).
    """
    name = models.CharField(max_length=200, help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)")

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name


class Author(models.Model):
    """
    Model representing an author.
    """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    def get_absolute_url(self):
        """
        Returns the url to access a particular author instance.
        """
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return '%s %s' % (self.first_name, self.last_name)


class Book(models.Model):
    """
    Model representing a book (but not a specific copy of a book).
    """
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file.
    description = models.TextField(max_length=1000, help_text="Enter a brief description of the book")
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined, so we can specify the object above.
    price = models.DecimalField(max_digits=7, decimal_places=2)
    digital = models.BooleanField(blank=True, default=False, null=True)
    pages = models.IntegerField()
    created = models.DateField(default=timezone.now, null=True, blank=True)
    count = models.IntegerField(default=0)
    available = models.BooleanField(default=True)
    storehouse_book_id = models.CharField(max_length=50, null=True, help_text='Book id from storehouse')

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title

    def status_book(self):
        if self.count < 1:
            return self.available is False
        else:
            return self.available is True

    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('book-detail', args=[str(self.id)])

shop/templates/shop/include/filter.html
{% load static %}

<h3 class="mb-4 border-bottom pb-1">Filters</h3>
<form method="GET" action="">

    <div class="card mb-4">
        <h6 class="card-header">Price</h6>
        <div class="list-group list-group-flush">
            <label for="amount" style="margin-top: 10px !important; margin-bottom: 10px !important;">PriceFrom ${{ min_price.price__min }}</label>
            <input class="form-control" style="width: 148px !important; margin-left: 50px !important;" type="text" id="id_price_0" name="price_min" value="{{ filter.form.data.price_min }}">

            <label for="amount" style="margin-top: 10px !important; margin-bottom: 10px !important;">PriceTo ${{ max_price.price__max }}</label>
            <input class="form-control" style="margin-bottom: 20px !important; width: 148px !important; margin-left: 50px !important;" type="text" id="id_price_1" name="price_max"  value="{{ filter.form.data.price_max }}">

        </div>
    </div>

    <div class="card mb-4">
        <h6 class="card-header">Genre</h6>
        <div class="list-group list-group-flush">
            {% for filter in filter.form.fields.genre.queryset.all %}
                <li class="list-group-item">
                    <input class="filter-checkbox" name="genre" id="id_genre" value="{{ filter.id }}" type="checkbox">
                    {{ filter }}
                </li>
            {% endfor %}
        </div>
    </div>

    <div class="card mb-4">
        <h6 class="card-header">Authors</h6>
        <div class="list-group list-group-flush">
            <select class="form-select" name="author" id="id_author" aria-label="Default select example">
                <option value="">---------------------------</option>
                {% for filter in filter.form.fields.author.queryset.all %}
                    <option value="{{ filter.id }}">{{ filter }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <button class="btn btn-outline-dark" style="margin-bottom: 2px !important;">Filter</button>
    <a class="btn btn-outline-dark" style="margin: 20px 10px 20px 50px !important;" href="{% url 'store' %}">
          <span class="glyphicon glyphicon-plus"></span>
          Reset
    </a>
</form>

shop/templates/shop/include/pagination.html
<ul class="pagination justify-content-center" style="margin-top: 25px !important;">
    {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link">Previous</a>
        </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
            <li class="page-item"><a class="page-link" href="#">{{ i }} </a></li>
        {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link">Next</a>
        </li>
    {% endif %}
</ul>